export const whole = { xs: 12 }
export const twelfth = { xs: 12, md: 1 }
export const sixth = { xs: 12, md: 2 }
export const quarter = { xs: 12, md: 3 }
export const third = { xs: 12, md: 4 }
export const half = { xs: 12, md: 6 }
export const twoThirds = { xs: 12, md: 8 }
export const threeQuarters = { xs: 12, md: 9 }
export const fiveSixths = { xs: 12, md: 10 }
export const autoCol = { xs: 12, md: true }
