
export const transCommType = code => {
  switch (code) {
    case '**': return 'Asterisks'
    case '01': return 'PaperTitle'
    case '02': return 'ParkingViolations'
    case '03': return 'Registration'
    case '04': return 'LicensePlate'
    case '05': return 'TaxStatements'
    case '07': return 'EmissionTest'
    case '08': return 'UDriveIt'
    case '09': return 'TitleApplication'
    case '10': return 'Checks'
    case '11': return 'Request_Payoff'
    case '12': return 'Request_Retrieval'
    case '13': return 'ImpoundNotice'
    case '14': return 'TitleAppException'
    case '18': return 'ElectronicMessage'
    case '19': return 'RequestRepoRedemption'
    case '20': return 'Contract'
    case '29': return 'LetterLienSatisfaction'
    case '30': return 'RequestTitleNameChange'
    case '31': return 'RequestCustomerMoveNewTitle'
    case '32': return 'RequestReposessionNewTitle'
    case '33': return 'RequestLeaseToLoan'
    case '35': return 'DiscrepantTitleDMVLetter'
    case '36': return 'RequestLienSatisfaction'
    case '37': return 'LetterWithTitle'
    case '38': return 'LetterWithLienSat'
    case '44': return 'LetterTitleLeaseToCash'
    case '45': return 'LetterLienSatLeaseToCash'
    case '46': return 'DealerDiscrepantTitleLetter1'
    case '48': return 'DiscrepantTitleToDMVLetter'
    case '49': return 'RequestForDuplicate_NoTitleReceived'
    case '50': return 'DiscrepantTitleDealerLetter'
    case '51': return 'RequestReleaseUnidentified'
    case '52': return 'RequestRedirectUnidentifiedTitle'
    case '54': return 'DirectSaleTransfer'
    case '55': return 'TitleLienTransfer'
    case '56': return 'RequestPaperTitleCopy'
    case '57': return 'TitleDiscrepantDmvReturn'
    case '58': return 'RequestTitleDestroy'
    case '59': return 'NewLoanActionInternal'
    case '61': return 'PendingDiscrepantPerfected'
    case '62': return 'RequestDMVDealerRetrieval'
    case '63': return 'RequestDestroyLienNotice'
    case '64': return 'ReleaseOfLien or RequestELTActionReleaseOfLien'
    case '65': return 'ReleaseLien3rdParty or RequestELTActionReleaseOfLienThirdParty'
    case '66': return 'PrintTitle or equestELTActionPrintTitle'
    case '67': return 'LienCorrection or RequestELTActionLienCorrection'
    case '68': return 'Lien3rdPrtyUpdateRegistration or RequestELTActionReleaseOfLienThirdPartyUpdateReg or RequestELTActionReleaseOfLienThirdPartyUpdateReg'
    case '69': return 'CAReleaseLien or RequestELTActionCA227ReleaseOfLien'
    case '70': return 'LienTransfer or RequestELTActionLienTransfer'
    case '71': return 'CAChangeCustomerAddress or RequestELTActionChangeCustomerAddress'
    case '72': return 'LienChangeCustomerAddress or RequestELTActionReleaseOfLienChangeCustomerAddress'
    case '73': return 'RequestELTActionUIDReleaseOfLien or UnidentifiedReleaseOfLien'
    case '74': return 'RequestELTActionUIDReleaseOfLienThirdParty or UnidentifiedReleaseLien3rdParty'
    case '75': return 'RequestELTActionUIDPrintTitle or UnidentifiedPrintTitle'
    case '76': return 'RequestELTActionUIDLienCorrection or UnidentifiedLienCorrection'
    case '77': return 'RequestELTActionUIDReleaseOfLienThirdPartyUpdateReg or UnidentifiedLien3rdPrtyUpdateRegistration'
    case '78': return 'RequestELTActionUIDCA227ReleaseOfLien or UnidentifiedCAReleaseLien'
    case '79': return 'RequestELTActionUIDLienTransfer or UnidentifiedLienTransfer'
    case '80': return 'RequestELTActionUIDChangeCustomerAddress or UnidentifiedCAChangeCustomerAddress'
    case '81': return 'RequestELTActionUIDReleaseOfLienChangeCustomerAddress or UnidentifiedLienChangeCustomerAddress'
    case '82': return 'ThankYouLetterELT'
    case '83': return 'RequestRepoToAuction'
    case '84': return 'LetterHyunThankYou or LetterThankYouTitleToCustomer'
    case '85': return 'LetterHyunThirdParty or LetterThankYouTitleToThirdParty'
    case '86': return 'LetterThirdPartyCvr'
    case '87': return 'LetterHyunPermission'
    case '88': return 'LetterHyunPoa'
    case '89': return 'LetterHyundaiBillOfSale'
    case '91': return 'ThankYouLetter'
    case '92': return 'EmergencyPTPrintTitle or RequestELTActionEmergencyPrintTitle'
    case '93': return 'RequestELTActionUIDEmergencyPrintTitle or UnidentifiedEmergencyPrintTitle'
    case '96': return 'LetterHyundaiTitleCopy'
    case '97': return 'RequestELTTitleCopy'
    case '98': return 'OtherBranch'
    case '99': return 'OtherCustomer'
    case 'A1': return 'ReleaseOfSecondLien or RequestELTActionReleaseOfSecondLien'
    case 'A2': return 'RequestELTActionUIDReleaseOfSecondLien or UnidentifiedReleaseOfSecondLien'
    case 'A4': return 'RequestFloridaELTRepo'
    case 'A5': return 'RequestForDuplicate_Internal_NoTitleReceived'
    case 'A6': return 'RequestRepoContractOnly'
    case 'A8': return 'Request_LeaseBuyOut'
    case 'A9': return 'DiscrepantELTtoDMVLetter'
    case 'B1': return 'DiscrepantELTToDealerLetter'
    case 'B2': return 'DMVDiscrepantELTLetter'
    case 'B3': return 'DealerDiscrepantELTLetter'
    case 'B4': return 'RequestELTActionAcceptTDNNotification'
    case 'B5': return 'RequestELTActionDisputeTDNNotification'
    case 'B6': return 'RequestTransferOfEquity'
    case 'B7': return 'RequestForTitleApplication'
    case 'B8': return 'RequestForLienAssignment'
    case 'B9': return 'LetterUpstartPermission'
    case 'C1': return 'LetterFMCCPoa'
    case 'C2': return 'LetterFMCCPermission'
    case 'C3': return 'RequestCustomerMoveNewWithoutTitle'
    case 'C4': return 'LetterFMCCLienSatToo'
    case 'C5': return 'LetterFMCCLienSatPoa'
    case 'C6': return 'LetterFMCCTRACBos'
    case 'C7': return 'RequestMileageCorrection'
    case 'DN': return 'DemandNotice'
    case 'E1': return 'ElectronicTitle'
    case 'E2': return 'NewLoanActionExternal'
    case 'N4': return 'RequestNonFloridaELTRepo'
    case 'N5': return 'ExpeditedPTPrintTitle or RequestELTActionExpeditedPrintTitle'
    case 'N6': return 'RequestELTActionUIDExpeditedPrintTitle or UnidentifiedExpeditedPrintTitle'
    case 'S1': return 'SecondTitle'
    case 'SP': return 'SubPoena'
    case 'T1': return 'LetterTMCCBillOfSale'
    case 'T2': return 'LetterTMCCPoa'
    case 'T3': return 'LetterTMCCPermission'
    case 'T4': return 'ThankYouLetterELTThirdParty'
    case 'T5': return 'LetterTMCCNameChange'
    case 'T6': return 'LetterTMCCCustomerMove'
    case 'V7': return 'LetterVWPermission'
    case 'V8': return 'LetterVWPoa'
    default: return ''
  }
}

export const transBusCode = code => {
  switch (code) {
    case '01': return 'Retail'
    case '02': return 'Lease'
    case '07': return 'CompanyCars'
    case '09': return 'FMCCTRACBusUnit'
    case '10': return 'DealerServices'
    case '11': return 'Ducati'
    case '14': return 'VehicleServices'
    case '99': return 'Default'
    default: return ''
  }
}

export const transClientCode = code => {
  switch (code) {
    case '0002': return 'FMCC'
    case '0003': return 'Fairlane'
    case '0004': return 'Primus'
    case '0005': return 'Toyota'
    case '0006': return 'Volkswagen'
    case '0007': return 'Hyundai'
    case '0008': return 'ToyotaFinancialServices'
    case '0009': return 'ToyotaTracLCCS'
    case '0010': return 'ToyotaMazda'
    case '0011': return 'UpstartNetworkInc'
    case '3001': return 'NicholasFinancial'
    case '3002': return 'FloridaParishesBank'
    case '5000': return 'FinancialInstitution'
    default: return ''
  }
}

export const transActivityCode = code => {
  switch (code) {
    case '01': return 'VerificationPerfect'
    case '02': return 'VerificationDiscrepant'
    case '03': return 'VerificationPaperlessPerfect'
    case '04': return 'VerificationPaperlessDiscrepant'
    case '05': return 'GenerateFollowUpLetter'
    case '06': return 'FollowUpBranchInitiated'
    case '07': return 'WaiverClientUpdate'
    case '08': return 'LeaseDocumentRedirect'
    case '09': return 'ReleaseTitle'
    case '10': return 'WaiverOfFollowUpOrDiscrepancy'
    case '11': return 'UnidentifiedTitleRedirect'
    case '12': return 'UnidentifiedLeaseDocRedirect'
    case '13': return 'ForceFollowUpClientInitiated'
    case '14': return 'ExpeditedTitle'
    case '15': return 'UpdateTitleStatus'
    case '16': return 'MisIdentifiedTitle'
    case '17': return 'FollowUpLetterMailed'
    case '18': return 'FollowUpReportOnly'
    case '19': return 'FollowUp3rdLetterSent'
    case '20': return 'PrintRequestElt'
    case '21': return 'ReleaseOfLienElt'
    case '22': return 'RejectLienElt'
    case '23': return 'ReleaseLienChangeAddress'
    case '24': return 'ReleaseLienThirdParty'
    case '25': return 'NewFollowUpClientUpdate'
    case '26': return 'InboundCall'
    case '27': return 'OutboundCallToDmv'
    case '28': return 'OutboundCallToDealer'
    case '29': return 'InquiryRequestFree'
    case '30': return 'ContractReceived'
    case '31': return 'DocumentsRetrieved'
    case '32': return 'ReleasedTitleOnRetreivalRequest'
    case '33': return 'ReleasedContractOnRetrievalRequest'
    case '34': return 'ReleasedContractOnPayoffRequest'
    case '35': return 'ProcessedPayoff'
    case '36': return 'ProcessedRetrieval'
    case '37': return 'ReceivedTitleServiceRequest'
    case '38': return 'DiscrepantDealerLetter'
    case '39': return 'TitleServiceRequestProcessed'
    case '40': return 'TitleServiceFollowUpLetter'
    case '41': return 'ReceivedExpeditedTitleServiceRequest'
    case '42': return 'ExpeditedTitleServiceRequestProcessed'
    case '43': return 'TitleServiceRejectedNoPaperTitle'
    case '44': return 'TitleServiceRejectedAcctBeingServiced'
    case '45': return 'PendingDiscrepantTitle'
    case '46': return 'TitleServicesComment'
    case '47': return 'FollowUpComment'
    case '48': return 'LeaseToLoanSentToDmv'
    case '49': return 'TitleServiceExhausted'
    case '50': return 'UnmatchedPendingDiscrepantTitle'
    case '51': return 'CancelledTitleServiceRequest'
    case '52': return 'ReprocessedTitleServiceRequest'
    case '53': return 'TitleServiceCredit'
    case '54': return 'TitleServiceRequestSentOut'
    case '55': return 'ExpeditedTitleServiceRequestSentOut'
    case '56': return 'TitleServiceRequestSentOutNoFee'
    case '57': return 'ManualTitleRetrieval'
    case '58': return 'VerificationPerfectByClient'
    case '59': return 'TitleVerification'
    case '60': return 'ExpeditedEltAction'
    case '61': return 'EltPaperLienSatisfied'
    case '62': return 'LienNoticeReceived'
    case '63': return 'PendingDiscrepantOverlaid'
    case '64': return 'InquiryRequestWithFee'
    case '65': return 'ReviewResearchTheAccount'
    case '66': return 'StateEmailInquiry'
    case '67': return 'OutboundFax'
    case '68': return 'InboundFax'
    case '69': return 'RequestForTitleLetter'
    case '70': return 'NewFollowUpExhausted'
    case '71': return 'MoveFollowUpExhausted'
    case '72': return 'DiscrepantFollowUpExhausted'
    case '73': return 'WaiveStatusDealerResponsible'
    case '74': return 'WaiveStatusDealerNotResponsible'
    case '75': return 'InboundCallExternal'
    case '76': return 'OutboundCallToDmvExternal'
    case '77': return 'OutboundCallToDealerExternal'
    case '78': return 'InquiryRequestFreeExternal'
    case '79': return 'InquiryRequestWithFeeExternal'
    case '80': return 'ReleaseOfLienRo'
    case '81': return 'ReleaseLienMailTo3rdPartyLo'
    case '82': return 'PrintTitlePt'
    case '83': return 'LienCorrectionLe'
    case '84': return 'ReleaseLienMailTo3rdPartyNoUpdtRegDi'
    case '85': return 'Ca227ReleaseLienRe'
    case '86': return 'LienTransferLt'
    case '87': return 'ChangeCustomersAddressCa'
    case '88': return 'ReleaseLienChangeCustomersAddressRa'
    case '89': return 'EltConfirmed'
    case '90': return 'EltActionCancelled'
    case '91': return 'EltRejected'
    case '92': return 'BrandedRecordReceived'
    case '93': return 'ClientInitiatedManualTransfer'
    case '94': return 'ReviewResearchTheAccountExternal'
    case '95': return 'Ticket'
    case '96': return 'StateEmailInquiryExternal'
    case '97': return 'MiscellaneousUpdateOrBranchSplitUpdate'
    case '98': return 'NonTrackedPaidOut'
    case '99': return 'OutboundFaxExternal'
    case 'A1': return 'InboundFaxExternal'
    case 'A2': return 'LetterSentToDealerExternal'
    case 'A3': return 'LetterSentToCustomerExternal'
    case 'A4': return 'OutboundCallToCustomerExternal'
    case 'A5': return 'InboundCustomerCallExternal'
    case 'A6': return 'LetterSentToDealer'
    case 'A7': return 'LetterSentToCustomer'
    case 'A8': return 'OutboundCallToCustomer'
    case 'A9': return 'InboundCustomerCall'
    case 'B1': return 'S2sDmvCustomerLetter'
    case 'B2': return 'MarylandCitation'
    case 'B3': return 'UpdateAccountStatus'
    case 'B4': return 'FraudBlock'
    case 'B5': return 'TitlePendingResearch'
    case 'B6': return 'ManualEltInsert'
    case 'B7': return 'NmvtisInquiryRequestExternal'
    case 'B8': return 'NmvtisInquiryRequest'
    case 'B9': return 'EltRejectResearch'
    case 'C1': return 'DiscrepancyReview'
    case 'VA': return 'AdhocLimitedPowerOfAttorney'
    case 'VL': return 'AdhocLiensatLetter'
    case 'VR': return 'AdhocDmvRecallLetter'
    case 'VS': return 'AdhocS2sTransferLetter'
    case 'VT': return 'AdhocTransferOfEquityLetter'
    default: return ''
  }
}
